FROM postgres

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=pass123
ENV POSTGRES_DB=mydatabase
ENV POSTGRES_SCHEMA=public
ENV POSTGRES_PORT=5432

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432